import { makeCreateBillingControlUseCase } from '@/use-cases/factories/make-create-billing-control-use-case'
import { FastifyRequest, FastifyReply } from 'fastify'
import { z } from 'zod'

export async function create(req: FastifyRequest, res: FastifyReply) {
  const createBodySchema = z.object({
    idInquilino: z.coerce.number(),
    idUsina: z.coerce.number(),
    contribCusteioIpCip: z.coerce.number(),
    cpflInquilino: z.coerce.number().nullable().default(null),
    credAdcBandTarifaria: z.coerce.number(),
    creditoDebito: z.coerce.number(),
    economia: z.coerce.number().nullable().default(null),
    incentivoInquilinoInvestidor: z.coerce.number().nullable().default(null),
    inquilinoPagar: z.coerce.number().nullable().default(null),
    investidorReceber: z.coerce.number().nullable().default(null),
    kwhAtivo: z.coerce.number().nullable().default(null),
    kwhInjetado: z.coerce.number(),
    kwhMinimo: z.coerce.number(),
    leitura1: z.string().nullable().default(null),
    leitura2: z.string().nullable().default(null),
    mes: z.string(),
    mesRef: z.string().nullable().default(null),
    minimoInvestidor: z.coerce.number(),
    observacao: z.string().nullable().default(null),
    saldoBancoAnterior: z.coerce.number(),
    saldoBancoAtual: z.coerce.number().nullable().default(null),
    tarifaTeFv: z.coerce.number(),
    tarifaTusdFv: z.coerce.number(),
    taxaAdmSoluttion: z.coerce.number().nullable().default(null),
    totalCreditado: z.coerce.number().nullable().default(null),
    totalTarifasFv: z.coerce.number(),
    mesContratoSoluttion: z.string(),
  })

  const {
    contribCusteioIpCip,
    cpflInquilino,
    credAdcBandTarifaria,
    creditoDebito,
    economia,
    idInquilino,
    idUsina,
    incentivoInquilinoInvestidor,
    inquilinoPagar,
    investidorReceber,
    kwhAtivo,
    kwhInjetado,
    kwhMinimo,
    leitura1,
    leitura2,
    mes,
    mesContratoSoluttion,
    mesRef,
    minimoInvestidor,
    observacao,
    saldoBancoAnterior,
    saldoBancoAtual,
    tarifaTeFv,
    tarifaTusdFv,
    taxaAdmSoluttion,
    totalCreditado,
    totalTarifasFv,
  } = createBodySchema.parse(req.body)

  const createUserUseCase = makeCreateBillingControlUseCase()

  const { billingControl } = await createUserUseCase.execute({
    contribCusteioIpCip,
    cpflInquilino,
    credAdcBandTarifaria,
    creditoDebito,
    economia,
    idInquilino,
    idUsina,
    incentivoInquilinoInvestidor,
    inquilinoPagar,
    investidorReceber,
    kwhAtivo,
    kwhInjetado,
    kwhMinimo,
    leitura1,
    leitura2,
    mes,
    mesContratoSoluttion,
    mesRef,
    minimoInvestidor,
    observacao,
    saldoBancoAnterior,
    saldoBancoAtual,
    tarifaTeFv,
    tarifaTusdFv,
    taxaAdmSoluttion,
    totalCreditado,
    totalTarifasFv,
  })

  return res.status(200).send({ billingControl })
}
